linters:
  Indentation:
    width: 4
  NestingDepth:
    ignore_parent_selectors: true
  DeclarationOrder:
    enabled: false
  TransitionAll:
    enabled: true
  SelectorFormat:
    convention: hyphenated_BEM
